#!/usr/bin/env node
// Generates supabase/migrations/20260430100000_nevo_seed.sql from the NEVO CSV
// and the curated unit_grams JSON. Run: node scripts/import-nevo.js
//
// Inputs:
//   scripts/data/nevo-2025-9.csv          - RIVM source (gitignored)
//   scripts/data/nevo-unit-grams.json     - curated nevo_code -> grams_per_piece
// Output:
//   supabase/migrations/20260430100000_nevo_seed.sql

const fs = require('fs');
const path = require('path');

const CSV_PATH    = path.join(__dirname, 'data', 'nevo-2025-9.csv');
const UNITS_PATH  = path.join(__dirname, 'data', 'nevo-unit-grams.json');
const OUT_PATH    = path.join(__dirname, '..', 'supabase', 'migrations', '20260430100000_nevo_seed.sql');

// CSV column names we expect in the NEVO export.
// If RIVM uses different headers (English vs Dutch), update these.
const COL_CODE    = 'NEVO-code';
const COL_NAME    = 'Voedingsmiddelnaam';
const COL_SYNS    = 'Synoniem';
const COL_KCAL    = 'kcal (kcal)';

// --- Tiny CSV parser (RFC 4180-ish, supports quoted fields with delimiter inside).
function parseCsv(text) {
  if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);

  const firstNl = text.indexOf('\n');
  const headerLine = text.slice(0, firstNl);
  const delim = headerLine.includes(';') ? ';' : ',';

  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') { inQuotes = false; }
      else { field += c; }
    } else {
      if (c === '"') inQuotes = true;
      else if (c === delim) { row.push(field); field = ''; }
      else if (c === '\r') { /* skip */ }
      else if (c === '\n') {
        row.push(field); field = '';
        if (row.length > 1 || row[0] !== '') rows.push(row);
        row = [];
      } else field += c;
    }
  }
  if (field !== '' || row.length > 0) { row.push(field); rows.push(row); }

  const [header, ...data] = rows;
  return data.map(r => Object.fromEntries(r.map((v, i) => [header[i], v])));
}

function sqlString(s) {
  if (s == null || s === '') return 'null';
  return `'${String(s).replace(/'/g, "''")}'`;
}
function sqlArray(arr) {
  if (!arr || arr.length === 0) return 'null';
  return `array[${arr.map(sqlString).join(',')}]::text[]`;
}
function sqlInt(s) {
  const n = parseInt(String(s).replace(',', '.'), 10);
  return Number.isFinite(n) && n > 0 ? String(n) : null;
}

function main() {
  if (!fs.existsSync(CSV_PATH)) {
    console.error(`ERROR: NEVO CSV not found at ${CSV_PATH}`);
    console.error('Download NEVO 2025/9.0 from https://www.rivm.nl/nederlands-voedingsstoffenbestand');
    console.error('Save the CSV as scripts/data/nevo-2025-9.csv (gitignored).');
    process.exit(1);
  }

  const csvText  = fs.readFileSync(CSV_PATH, 'utf8');
  const records  = parseCsv(csvText);
  const unitsRaw = JSON.parse(fs.readFileSync(UNITS_PATH, 'utf8'));
  const units = Object.fromEntries(
    Object.entries(unitsRaw).filter(([k]) => !k.startsWith('_'))
  );

  let kept = 0, skippedNoKcal = 0;
  const inserts = [];

  for (const r of records) {
    const code = (r[COL_CODE] || '').trim();
    const name = (r[COL_NAME] || '').trim();
    const kcal = sqlInt(r[COL_KCAL]);
    if (!code || !name) continue;
    if (!kcal) { skippedNoKcal++; continue; }

    const syns = (r[COL_SYNS] || '')
      .split(/[,;]/)
      .map(s => s.trim())
      .filter(Boolean);

    const unitGrams = units[code] != null ? String(units[code]) : 'null';

    inserts.push(
      `insert into public.products (name, kcal_per_100g, unit_grams, source, nevo_code, synonyms, created_by) ` +
      `values (${sqlString(name)}, ${kcal}, ${unitGrams}, 'nevo', ${sqlString(code)}, ${sqlArray(syns)}, null) ` +
      `on conflict (nevo_code) do nothing;`
    );
    kept++;
  }

  const out = [
    '-- Migration: NEVO 2025/9.0 seed inserts',
    '-- Generated by scripts/import-nevo.js',
    '-- Source: NEVO-online versie 2025/9.0, RIVM, Bilthoven',
    `-- Records inserted: ${kept} (skipped ${skippedNoKcal} without kcal)`,
    '',
    ...inserts,
    '',
  ].join('\n');

  fs.writeFileSync(OUT_PATH, out, 'utf8');
  console.log(`Wrote ${OUT_PATH}`);
  console.log(`  kept:           ${kept}`);
  console.log(`  skipped no kcal: ${skippedNoKcal}`);
  console.log(`  unit_grams set:  ${Object.keys(units).length}`);
}

main();
